/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazdeusuario;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.Asignatura;
import modelo.Modulo;

/**
 *
 * @author brentheftye
 */
public class VistaVerPlanDeEstudio extends javax.swing.JFrame {
    ArrayList<Modulo> modulos;
    
    /**
     * Creates new form VistaVerPlanDeEstudio.
     * @param modulos Módulos del plan de estudio. 
     */
    public VistaVerPlanDeEstudio(ArrayList<Modulo> modulos) {
        initComponents();
        CentradorDeVistas.getCentradorDeVistas().centrarJFrame(this);
        this.modulos = modulos;
        llenarListaDeAsignaturasCreadas();
    }
    
    /**
     * Creates new form VistaVerPlanDeEstudio
     */
    public VistaVerPlanDeEstudio() {
        initComponents();
        CentradorDeVistas.getCentradorDeVistas().centrarJFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePlanDeEstudio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombrePlanDeEstudio.setText("Nombre");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Plan de Estudio");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(nombrePlanDeEstudio))
                    .add(layout.createSequentialGroup()
                        .add(270, 270, 270)
                        .add(jLabel2)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 106, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton1)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 463, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nombrePlanDeEstudio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 430, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Método que crea los titulos de la tabla a mostrar.
     *
     * @return Vector Títulos de la JTable.
     */
    private Vector llenarTitulosDeTabla() {
        Vector titulos = new Vector();
        titulos.add("Clave");
        titulos.add("Nombre");
        titulos.add("Créditos");
        titulos.add("Duración(Semanas)");
        titulos.add("Módulo");
        return titulos;
    }

    /**
     * Método que crea y llena una fila de la tabla con datos de una asignatura.
     *
     * @param asignatura Instancia.
     * @return Vector<String> Vector fila con los datos de la asignatura.
     */
    private Vector<String> llenarFilaDatosDeAsignatura(Asignatura asignatura) {
        Asignatura asignaturaIndexada = asignatura;
        Vector<String> filaDatosDeAsignaturaIndexada = new Vector<String>();
        filaDatosDeAsignaturaIndexada.add(asignaturaIndexada.getClave());
        filaDatosDeAsignaturaIndexada.add(asignaturaIndexada.getNombreAsignatura());
        filaDatosDeAsignaturaIndexada.add(asignaturaIndexada.getCreditos() + "");
        filaDatosDeAsignaturaIndexada.add(asignaturaIndexada.getDuracion() + "");
        return filaDatosDeAsignaturaIndexada;
    }

    /**
     * Método que llena la Tabla con las filas de las asignaturas.
     */
    private void llenarListaDeAsignaturasCreadas() {
        Vector titulosTabla = llenarTitulosDeTabla();
        Vector datosAsignaturas = new Vector<Vector<String>>();
        int numeroDeModulos = this.modulos.size();
        for (int i = 0; i < numeroDeModulos; i++) {
            Modulo moduloIndexado = modulos.get(i);
            int numeroDeAsigaturasDeModuloIndexado = moduloIndexado.getAsignaturas().size();
            for (int j = 0; j < numeroDeAsigaturasDeModuloIndexado; j++) {
                Vector<String> filaDatosDeAsignaturaIndexada = llenarFilaDatosDeAsignatura(moduloIndexado.getAsignaturas().get(j));
                filaDatosDeAsignaturaIndexada.add(moduloIndexado.getNombre());
                datosAsignaturas.add(filaDatosDeAsignaturaIndexada);
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(datosAsignaturas, titulosTabla) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jTable1.setModel(modelo);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVerPlanDeEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVerPlanDeEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVerPlanDeEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVerPlanDeEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVerPlanDeEstudio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombrePlanDeEstudio;
    // End of variables declaration//GEN-END:variables
}
